"use client"
import Link from "next/link"
import { useState, type FormEvent } from "react"
import { ArrowLeft, Globe2, Loader2, Search } from "lucide-react"

type CaseOption = { id: string; case_number: string | null; title: string | null; status: string | null }
type Json = Record<string, unknown>
const sections: Array<[string, string[]]> = [
  ["Domain / RDAP", ["rdap", "domain", "registration"]], ["DNS", ["dns", "dns_records"]],
  ["IP / ASN", ["ip", "ips", "network", "asn"]], ["HTTP", ["http", "web"]], ["TLS", ["tls", "certificate"]],
  ["Certificate Transparency", ["certificate_transparency", "ct"]], ["Infrastructure Correlation", ["correlations", "relationships"]],
  ["Findings", ["findings"]], ["Evidence", ["evidence", "artifacts"]],
]
function asObject(value: unknown): Json | null { return value && typeof value === "object" && !Array.isArray(value) ? value as Json : null }
function pick(data: Json, keys: string[]) { for (const key of keys) if (data[key] !== undefined && data[key] !== null) return data[key]; return null }
function count(value: unknown) { return Array.isArray(value) ? value.length : asObject(value) ? Object.keys(value as Json).length : value == null ? 0 : 1 }
function display(value: unknown) { if (value === null || value === undefined || value === "") return "Unavailable"; return typeof value === "object" ? JSON.stringify(value, null, 2) : String(value) }
function DataSection({ title, value }: { title: string; value: unknown }) {
  if (value == null || (Array.isArray(value) && !value.length)) return null
  const record = asObject(value)
  return <section className="rounded-md border border-[#143b28] bg-[#06110f] p-5"><h2 className="font-semibold text-white">{title}</h2>{record ? <dl className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(record).map(([key,val])=><div key={key} className="min-w-0 rounded border border-[#143b28] bg-black/20 p-3"><dt className="text-xs uppercase text-white/40">{key.replaceAll("_"," ")}</dt><dd className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-white/70">{display(val)}</dd></div>)}</dl> : Array.isArray(value) ? <div className="mt-4 space-y-3">{value.map((item,index)=><pre key={index} className="overflow-x-auto whitespace-pre-wrap break-words rounded border border-[#143b28] bg-black/25 p-3 text-xs leading-6 text-white/70">{display(item)}</pre>)}</div> : <p className="mt-3 break-words text-sm text-white/70">{display(value)}</p>}</section>
}

export default function DomainIntelligenceWorkspace({ cases, initialCaseId }: { cases: CaseOption[]; initialCaseId: string }) {
  const [caseId,setCaseId]=useState(initialCaseId), [domain,setDomain]=useState("")
  const [status,setStatus]=useState<"ready"|"analyzing"|"completed"|"failed">("ready"), [error,setError]=useState(""), [result,setResult]=useState<Json|null>(null)
  async function analyze(event: FormEvent) { event.preventDefault(); if(!caseId){setError("Select an authorized case before analysis.");return} setStatus("analyzing");setError("");setResult(null);try{const response=await fetch("/api/intelligence/domains/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({case_id:caseId,domain})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error||"Analysis failed.");setResult(data.analysis);setDomain(data.domain);setStatus("completed")}catch(reason){setError(reason instanceof Error?reason.message:"Analysis failed.");setStatus("failed")}}
  const selected=cases.find(item=>item.id===caseId), entities=result?pick(result,["entities"]):null, relationships=result?pick(result,["relationships","correlations"]):null, findings=result?pick(result,["findings"]):null, evidence=result?pick(result,["evidence","artifacts"]):null
  return <div className="space-y-6"><header className="border-b border-[#143b28] pb-6"><Link href="/dashboard/intelligence" className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-[#20dc73]"><ArrowLeft className="h-4 w-4"/>Intelligence Workspace</Link><div className="mt-5 flex items-center gap-3"><Globe2 className="h-7 w-7 text-[#20dc73]"/><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-[#20dc73]">Case-scoped analysis</p><h1 className="text-3xl font-bold">Domain Intelligence</h1></div></div><p className="mt-3 max-w-3xl text-sm leading-6 text-white/55">Analyze lawful domain infrastructure through SDIA. Correlations are investigative leads, not proof of ownership or wrongdoing.</p></header>
    <form onSubmit={analyze} className="grid gap-4 rounded-md border border-[#143b28] bg-[#06110f] p-5 lg:grid-cols-[1fr_1fr_auto]"><label className="text-sm text-white/65">Authorized case<select value={caseId} onChange={e=>setCaseId(e.target.value)} required className="mt-2 h-11 w-full rounded border border-[#24563d] bg-black/30 px-3 text-white"><option value="">Select case</option>{cases.map(item=><option key={item.id} value={item.id}>{item.case_number||"Case"} — {item.title||"Untitled"}</option>)}</select></label><label className="text-sm text-white/65">Domain<input value={domain} onChange={e=>setDomain(e.target.value)} required placeholder="example.com" autoComplete="off" className="mt-2 h-11 w-full rounded border border-[#24563d] bg-black/30 px-3 text-white outline-none focus:border-[#20dc73]"/></label><button disabled={status==="analyzing"||!caseId} className="mt-auto inline-flex h-11 items-center justify-center gap-2 rounded bg-[#20dc73] px-5 font-semibold text-black disabled:opacity-50">{status==="analyzing"?<Loader2 className="h-4 w-4 animate-spin"/>:<Search className="h-4 w-4"/>}{status==="analyzing"?"Analyzing...":"Analyze Domain"}</button></form>
    <div className="flex flex-wrap items-center gap-3 text-sm"><span className="rounded border border-[#24563d] px-3 py-1.5 capitalize text-[#20dc73]">{status}</span>{selected&&<span className="text-white/50">Associated with {selected.case_number||selected.title}</span>}<span className="text-amber-200/70">Results are not permanently saved.</span></div>
    {!cases.length&&<div className="rounded border border-amber-400/30 bg-amber-400/10 p-4 text-sm text-amber-100">No active case with an investigative assignment is available.</div>}{error&&<div role="alert" className="rounded border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
    {result&&<><section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Entities",count(entities)],["Relationships",count(relationships)],["Findings",count(findings)],["Evidence artifacts",count(evidence)]].map(([label,value])=><div key={String(label)} className="rounded-md border border-[#143b28] bg-[#06110f] p-4"><p className="text-xs uppercase text-white/40">{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p></div>)}</section>{sections.map(([title,keys])=><DataSection key={title} title={title} value={pick(result,keys)}/>)}<details className="rounded-md border border-[#143b28] bg-[#06110f] p-5"><summary className="cursor-pointer font-semibold text-white">Raw intelligence JSON</summary><pre className="mt-4 max-h-[36rem] overflow-auto whitespace-pre-wrap break-words rounded bg-black/30 p-4 text-xs leading-6 text-white/65">{JSON.stringify(result,null,2)}</pre></details><p className="text-xs leading-5 text-white/45">Certificate Transparency hostnames may be historical or inactive. Shared IP addresses and ASNs do not by themselves establish common ownership.</p></>}
  </div>
}
